export type GlobalPermission =
  | 'TENANT_CREATE'
  | 'TENANT_ACT_AS_ANY'
  | 'TENANT_MEMBER_MANAGE_ANY'
  | 'TENANT_ACCESS_GROUP_MANAGE_ANY'
  | 'TENANT_PERMISSION_GRANT_MANAGE_ANY'
  | 'STAFF_PERMISSION_MANAGE'
  | 'STAFF_USER_CREATE'
  | 'STAFF_USER_VIEW'
  | 'DASHBOARD_VIEW_GLOBAL'
  | 'AUDIT_TRAIL_VIEW'
  | 'PROFILE_EDIT';

export const ALL_GLOBAL_PERMISSIONS: GlobalPermission[] = [
  'TENANT_CREATE',
  'TENANT_ACT_AS_ANY',
  'TENANT_MEMBER_MANAGE_ANY',
  'TENANT_ACCESS_GROUP_MANAGE_ANY',
  'TENANT_PERMISSION_GRANT_MANAGE_ANY',
  'STAFF_PERMISSION_MANAGE',
  'STAFF_USER_CREATE',
  'STAFF_USER_VIEW',
  'DASHBOARD_VIEW_GLOBAL',
  'AUDIT_TRAIL_VIEW',
  'PROFILE_EDIT',
];
