export type GlobalPermission =
  | 'TENANT_CREATE'
  | 'TENANT_ACT_AS_ANY'
  | 'STAFF_PERMISSION_MANAGE'
  | 'STAFF_USER_CREATE'
  | 'STAFF_USER_VIEW'
  | 'STAFF_USER_EDIT'
  | 'STAFF_USER_DELETE'
  | 'PROFILE_VIEW'
  | 'PROFILE_EDIT'
  | 'DASHBOARD_VIEW_GLOBAL'
  | 'AUDIT_TRAIL_VIEW'
  | 'STAFF_SUPPORT_HANDLE'
  | 'TENANT_VIEW'
  | 'TENANT_EDIT'
  | 'TENANT_DELETE'
  | 'TENANT_MEMBER_VIEW'
  | 'TENANT_MEMBER_CREATE'
  | 'TENANT_MEMBER_EDIT'
  | 'TENANT_MEMBER_DELETE'
  | 'TENANT_ACCESS_GROUP_VIEW'
  | 'TENANT_ACCESS_GROUP_CREATE'
  | 'TENANT_ACCESS_GROUP_EDIT'
  | 'TENANT_ACCESS_GROUP_DELETE'
  | 'TENANT_PERMISSION_GRANT_VIEW'
  | 'TENANT_PERMISSION_GRANT_CREATE'
  | 'TENANT_PERMISSION_GRANT_DELETE';

export const ALL_GLOBAL_PERMISSIONS: GlobalPermission[] = [
  'TENANT_CREATE',
  'TENANT_ACT_AS_ANY',
  'STAFF_PERMISSION_MANAGE',
  'STAFF_USER_CREATE',
  'STAFF_USER_VIEW',
  'STAFF_USER_EDIT',
  'STAFF_USER_DELETE',
  'PROFILE_VIEW',
  'PROFILE_EDIT',
  'DASHBOARD_VIEW_GLOBAL',
  'AUDIT_TRAIL_VIEW',
  'STAFF_SUPPORT_HANDLE',
  'TENANT_VIEW',
  'TENANT_EDIT',
  'TENANT_DELETE',
  'TENANT_MEMBER_VIEW',
  'TENANT_MEMBER_CREATE',
  'TENANT_MEMBER_EDIT',
  'TENANT_MEMBER_DELETE',
  'TENANT_ACCESS_GROUP_VIEW',
  'TENANT_ACCESS_GROUP_CREATE',
  'TENANT_ACCESS_GROUP_EDIT',
  'TENANT_ACCESS_GROUP_DELETE',
  'TENANT_PERMISSION_GRANT_VIEW',
  'TENANT_PERMISSION_GRANT_CREATE',
  'TENANT_PERMISSION_GRANT_DELETE',
];
