export type Permission =
  | 'TENANT_MEMBER_MANAGE'
  | 'ARTICLE_VIEW'
  | 'ARTICLE_CREATE'
  | 'ARTICLE_EDIT'
  | 'ARTICLE_DELETE'
  | 'CONVERSATION_USE'
  | 'DASHBOARD_VIEW';

export const ALL_PERMISSIONS: Permission[] = [
  'TENANT_MEMBER_MANAGE',
  'ARTICLE_VIEW',
  'ARTICLE_CREATE',
  'ARTICLE_EDIT',
  'ARTICLE_DELETE',
  'CONVERSATION_USE',
  'DASHBOARD_VIEW',
];
