package br.com.conectabyte.knowly.tenancy;

import br.com.conectabyte.knowly.softdelete.SoftDeleteFilter;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.concurrent.atomic.AtomicLong;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.Filter;
import org.hibernate.envers.Audited;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

@Entity
@Table(name = "tenants")
@Audited
@EntityListeners(AuditingEntityListener.class)
@Filter(name = SoftDeleteFilter.NAME)
@Getter
@Setter
@NoArgsConstructor
public class Tenant {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(name = "legal_name", nullable = false)
    private String legalName;

    @Column(name = "tax_id", nullable = false)
    private String taxId;

    @Column(nullable = false)
    private String country;

    @Column(name = "contact_email", nullable = false)
    private String contactEmail;

    @Column(name = "contact_phone", nullable = false)
    private String contactPhone;

    @Column(name = "postal_code", nullable = false)
    private String postalCode;

    @Column(nullable = false)
    private String street;

    @Column(nullable = false)
    private String number;

    @Column private String complement;

    @Column(nullable = false)
    private String neighborhood;

    @Column(nullable = false)
    private String city;

    @Column(nullable = false)
    private String state;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @CreatedBy
    @Column(name = "created_by", nullable = false, updatable = false)
    private String createdBy;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @LastModifiedBy
    @Column(name = "updated_by", nullable = false)
    private String updatedBy;

    /**
     * tenant-crud REQ-8: soft-delete marker -- null while active, set at the moment of deletion.
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    /**
     * Sequence backing the placeholder {@code taxId} generated by {@link #Tenant(String)} below --
     * guarantees uniqueness across the ~50 existing test fixtures that construct a bare {@code
     * Tenant(name)} without caring about company identification, without requiring every one of
     * them to be touched by tenant-creation (per TASKS.md's own file list, only a handful of
     * fixtures that assert on the dropped/added fields are in scope for this feature).
     */
    private static final AtomicLong PLACEHOLDER_SEQUENCE = new AtomicLong();

    /**
     * Test/legacy-fixture convenience constructor: fills every new mandatory field (REQ-2) with the
     * same sentinel-placeholder shape {@code V23}'s migration backfill uses for pre-existing rows,
     * so the ~50 test fixtures across this codebase that only care about {@code name} keep
     * compiling and passing {@code NOT NULL} constraints unmodified. Real tenant creation ({@link
     * br.com.conectabyte.knowly.tenancy.TenantService#createTenant}) always uses the full
     * constructor below instead.
     */
    public Tenant(String name) {
        this(
                name,
                name,
                "PENDING-" + PLACEHOLDER_SEQUENCE.incrementAndGet() + "-" + System.nanoTime(),
                "BR",
                "unset@example.invalid",
                "0000000000",
                "00000000",
                "unset",
                "unset",
                null,
                "unset",
                "unset",
                "unset");
    }

    public Tenant(
            String name,
            String legalName,
            String taxId,
            String country,
            String contactEmail,
            String contactPhone,
            String postalCode,
            String street,
            String number,
            String complement,
            String neighborhood,
            String city,
            String state) {
        this.name = name;
        this.legalName = legalName;
        this.taxId = taxId;
        this.country = country;
        this.contactEmail = contactEmail;
        this.contactPhone = contactPhone;
        this.postalCode = postalCode;
        this.street = street;
        this.number = number;
        this.complement = complement;
        this.neighborhood = neighborhood;
        this.city = city;
        this.state = state;
    }
}
